# Exported from Render on 2025-05-28T19:58:20Z
services:
- type: web
  name: cadastro_web_render
  runtime: python
  repo: https://github.com/AMS2025-phm/cadastro_web_render
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeployTrigger: commit
version: "1"
